---
title: Reproducibility in Scientific Computing

format:
  revealjs:
    theme: night
    logo: https://iccs.cam.ac.uk/sites/default/files/iccs_ucam_combined_reverse_colour.png

authors:
  - name: Jack Franklin
  - name: Marion Weinzierl
---

{{< include introduction.qmd >}}

# Version Control

- First put things into version control
- Then any changes/fixes can be tracked
- The repository can then also be hosted a remote service (e.g. GitHub, GitLab, Codeberg, Bitbucket)
- This will make collaboration with other people a lot easier!

# Documentation

- README
- User Docs
- Dev Docs
- Comments?

# Dependencies

- Basic documentation
- Project files (e.g. project.toml for python etc)
- System dependencies (nix/guix/docker?)

# Testing
- Unit tests
- Integration tests
- Automating tests (CI etc)

# FAIR Principles
- Findability
- Accessibility
- Interoperability
- Reuse

$-- Maybe we should look at this retrospectively, and see what elements we covered and
$-- where we could improve on.
$-- Also a good way to talk about why these are good principles to start a project with
$-- since we can show that they avoid most/all the problems that we had to solve

# Conclusion/Outlook

