# Version Control

## Version Control

- The first thing we should do is move our project into version control (VC)
- This way we never lose the original state of the project
- We can then try things without worrying about breaking anything!
- This will also benefit any later development, so the sooner the better

## What to add to VC

- DON'T do this:
``` bash
git add .
```

- Our repository should only contain:
  - Code/scripts
  - Documentation
  - Metadata
  - i.e. just text files

There will be some exceptions to this rule, but for the vast majority of cases
it will be true.

## What to add to VC

- Large datafiles should be hosted separately (e.g. on Zenodo)
- External dependencies should be declared
  - e.g. link to Zenodo dataset in docs and code
- Use .gitignore to automatically ignore any unwanted files
  - e.g. build outputs

## Aside - testing with worktrees

- git worktrees are like "local clones" of a repository
- Create a worktree:
``` bash
git worktree add -b <new-branch-name> <path>
```
- Will make a new directory, with only files that are tracked
- Can use as a cleanroom to ensure all dependencies are there
- For more info: `git worktree add --help`

## What to do next?

- The repository can then also be hosted a remote service (e.g. GitHub, GitLab, Codeberg, Bitbucket)
- This will make collaboration with other people a lot easier!
- It will also mean that any work done can be accessed by collaborators


